# TB Infection Model (Equations 1–5)
# Shiny app to explore parameter influence
# Author: Generated by ChatGPT

# ---- Load packages ----
if (!requireNamespace("shiny", quietly = TRUE)) install.packages("shiny")
if (!requireNamespace("deSolve", quietly = TRUE)) install.packages("deSolve")
if (!requireNamespace("ggplot2", quietly = TRUE)) install.packages("ggplot2")

library(shiny)
library(deSolve)
library(ggplot2)

# ---- ODE System (Equations 1–5) ----
mtb_model <- function(t, state, parms) {
  with(as.list(c(state, parms)), {
    # Eq 1: dMr/dt
    dMr <- sm + pm * Tb * Mr - ki * Tb * Mr - mu_m * Mr
    
    # Eq 2: dMib/dt
    dMib <- ki * Tb * Mr - kb * Mib - ka * (Mib / (Mib + A)) * T - kl * Mib * Cb - mu_mi * Mib
    
    # Eq 3: dTb/dt
    dTb <- kb * Nb * Mib - gamma1 * Tb * Mr - gamma2 * Tb * Cb + r_m * Tb + kl * Nc * Mib * Cb
    
    # Eq 4: dT/dt
    dT <- s_t + r1 * (T * Tb / (Tb + B)) - mu_t * T
    
    # Eq 5: dCb/dt
    dCb <- s_b + p_b * (Mib / (Mib + R_b)) * T * Cb - mu_cb * Cb

    list(c(dMr, dMib, dTb, dT, dCb))
  })
}

# ---- UI ----
ui <- fluidPage(
  titlePanel("Exploring the TB Infection Model (Equations 1–5)"),
  sidebarLayout(
    sidebarPanel(
      h4("Simulation Settings"),
      numericInput("days", "Simulation duration (days)", 600, min = 100, max = 2000, step = 50),
      h4("Initial Conditions"),
      numericInput("Mr0", "Mr(0)", 500),
      numericInput("Mib0", "Mib(0)", 0),
      numericInput("Tb0", "Tb(0)", 20),
      numericInput("T0", "T(0)", 1000),
      numericInput("Cb0", "Cb(0)", 5),
      hr(),
      h4("Key Parameters"),
      sliderInput("ki", "ki (infection rate)", 0, 0.001, 0.000025, step = 0.000005, sep=""),
      sliderInput("kb", "kb (burst rate)", 0, 0.001, 0.00002, step = 0.000005, sep=""),
      sliderInput("pm", "pm (Mr proliferation)", 0, 0.002, 0.000575, step = 0.00005, sep=""),
      sliderInput("r_m", "r_m (Tb multiplication)", 0, 0.5, 0.1, step = 0.01),
      actionButton("run", "Run Simulation", class = "btn-primary")
    ),
    mainPanel(
      tabsetPanel(
        tabPanel("Time Series", plotOutput("tsPlot", height = "600px")),
        tabPanel("Parameters", tableOutput("paramTable"))
      )
    )
  )
)

# ---- Server ----
server <- function(input, output, session) {

  # Full parameter set (constants + sliders)
  base_parms <- reactive({
    c(
      sm = 5, pm = input$pm, ki = input$ki, mu_m = 0.011,
      kb = input$kb, ka = 0.000125, A = 350, kl = 0.005, mu_mi = 0.011,
      Nb = 50, gamma1 = 0.00065, gamma2 = 0.02, r_m = input$r_m, Nc = 50,
      s_t = 10, r1 = 0.00001, B = 500, mu_t = 0.02,
      s_b = 5, p_b = 0.000001, R_b = 500, mu_cb = 0.95
    )
  })

  state0 <- reactive({
    c(Mr = input$Mr0, Mib = input$Mib0, Tb = input$Tb0, T = input$T0, Cb = input$Cb0)
  })

  sim_data <- eventReactive(input$run, {
    times <- seq(0, input$days, by = 1)
    ode(y = state0(), times = times, func = mtb_model, parms = base_parms()) |> as.data.frame()
  })

  output$tsPlot <- renderPlot({
    req(sim_data())
    df <- tidyr::pivot_longer(sim_data(), -time, names_to = "Variable", values_to = "Value")
    ggplot(df, aes(time, Value, colour = Variable)) +
      geom_line() +
      scale_y_continuous(trans = "log10") +
      labs(x = "Time (days)", y = "Population (log scale)") +
      theme_minimal()
  })

  output$paramTable <- renderTable({
    data.frame(Parameter = names(base_parms()), Value = unlist(base_parms()))
  }, striped = TRUE, spacing = "xs", width = "100%")
}

# ---- Launch app ----
shinyApp(ui, server)
